# name: Image Builder Deploy CI

# on:
#   push:
#     tags:
#       - '*'
#     branches:
#       - 'main'

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: hmarr/debug-action@v2

#     - name: Log in to the Container registry
#       uses: docker/login-action@v2
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}

#     # todo: have a way to commonize the docker image TAG creation
#     - name: Build and push image builder
#       uses: docker/build-push-action@v3
#       with:
#         context: .
#         push: true
#         tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
