name: Image Config Builder CI

on:
  push:
    branches-ignore:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure the Dockerfile
      run: python3 configure.py && cat Dockerfile

    - name: Upload Dockerfile context 
      uses: actions/upload-artifact@v3
      with:
        name: docker_context
        path: .

  build:
    runs-on: ubuntu-latest
    needs: configure
    container:
      image: ghcr.io/prb17/image-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}

    steps:
    - name: Download Dockerfile context result for 'configure'
      uses: actions/download-artifact@v3
      with:
        name: docker_context
    # - name: Log in to the Container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ${{ env.REGISTRY }}
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.PACKAGE_UPLOAD_TOKEN }}

    # todo: have a way to commonize the docker image TAG creation
    - name: Build the generated Dockerfile
      run: "ls -lR && export DOCKER_BUILD_CONTEXT=`pwd` && export DOCKER_BUILD_TAG=latest && export DOCKER_PUBLISH_REGISTRY=my-reg && entrypoint.sh"

    - name: Only Build desired image config
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"

