name: ubuntu-dev build
on:
  push:
    branches-ignore:
      - 'main'
  workflow_call:    

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  IMAGE_NAME: ubuntu-dev
  IMAGE_TAG: latest

jobs:
  configure:
    uses: ./.github/workflows/ubuntu-dev-config.yml
          
  build:
    runs-on: ubuntu-latest
    needs: configure
    container:
      image: ghcr.io/prb17/image-builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Download Dockerfile context result for 'configure'
      uses: actions/download-artifact@v3
      with:
        name: docker_context

    - name: Build the generated Dockerfile 
      run: |
        export DOCKER_BUILD_CONTEXT=`pwd` 
        export DOCKER_BUILD_IMAGE_NAME=${{ env.IMAGE_NAME }} 
        export DOCKER_BUILD_TAG=${{ env.IMAGE_TAG }} 
        entrypoint.sh
